server:
  port: 11001
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: yt4j-demo:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:${spring.application.name}.yml

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
  consumer:
    check: false

